GRANT USAGE ON DATABASE DATA_PIPELINE TO ROLE SYSADMIN;

GRANT USAGE ON SCHEMA DATA_PIPELINE.RAW TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA DATA_PIPELINE.STAGING TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA DATA_PIPELINE.MART TO ROLE SYSADMIN;

GRANT CREATE VIEW ON SCHEMA DATA_PIPELINE.STAGING TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA DATA_PIPELINE.MART TO ROLE SYSADMIN;

GRANT SELECT, INSERT, TRUNCATE
ON TABLE DATA_PIPELINE.RAW.USERS_RAW
TO ROLE SYSADMIN;